---
title: "Introducing multigitminder `r emo::ji('bee')`"
author: "Hayden MacDonald"
date: "2021-03-31"
output:
  blogdown::html_page:
    toc: false
slug: introducing-multigitminder
image_preview: ""
tags: 
- GitHub-Actions
- Python
- Docker
- Beeminder
- goals
- habits
description: "A GitHub Action for logging data points to Beeminder."
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(emo)
```

Setting new goals is easy, achieving them is hard.  

I have used a variety of tools over the years to help me achieve my goals. For the last couple of years, I've used a combination of Google Docs, Google Calendar, Google Keep, Loop Habit Tracker, Trello, and good ol' alarm clocks to schedule tasks and remind myself to get things done. Whether these goals were personal or professional, small or big, they would usually find their way into one of these tools with the hope that it would hold me accountable. 

When it came to my major goals (e.g. "do real good in school", "get a job"), these tools were more organizational than motivational. If a goal is truly important to me, I don't struggle to find motivation. Conversely, I have set many goals that sit in a grey area of motivation. These goals are much more difficult for me to achieve because they are deemed "not-so-important" or "not completely necessary", even though they are enjoyable and fulfilling activities. Unfortunately, their lack of priority means that they are often side-lined by major goals or leisurely activities.

Examples of these "not-so-important" goals include:

- Read 12 books this year
- Go for a run 3 times per week
- Meditate for 10 minutes every day

If you have set goals like these in the past, you will know how easy it is to never do them. The point is that the tools I was using to organize my goals were simple reminder engines. Reminders alone are useful, but only if you are motivated and organized at the very moment they arrive. If you are not, they have no real power. It is extremely easy to swipe away a push notification, especially when you are not in the mood for it. So for the last 6 months, I have been experimenting with a tool that has radically changed my mindset around these types of goals. That tool is [Beeminder](https://www.beeminder.com/){target="_blank"}.  

## "It's reminders with a sting!"

The simplified premise of Beeminder is as follows:

1. Set a goal
2. Create a commitment contract (e.g. "I will run 3 times per week")
3. Input your data (manually or automatically via app integrations)
4. Stay on track or Beeminder charges your credit card

In my experience, when I introduce Beeminder to people for the first time they usually think one of two things:

- "Wow, that sounds great!"
- "Wow, that app would take all my money."

Fair enough. Beeminder is not for everyone. For me, Beeminder provided the missing piece of the puzzle for my lower priority goals. Knowing that I could lose money from neglecting my goals forced me to decide [whether being lazy in the moment was truly worth it](https://forum.beeminder.com/t/beeminder-vs-cbt/7624/26?u=dreev){target="_blank"} or if I should just do what I said I was going to do.  

So I wholeheartedly endorse Beeminder for those who think they would be motivated by this kind of motivational scheme. It's worked great for me, particularly with keeping up with my reading and exercise goals through lockdown. I have lost money ($25 USD at time of writing) for forgetting to read or not finding the time to exercise, but using Beeminder has been completely worth it.  

## Programming goals

Since my initial success with the app, I've taken to Beeminding other goals. Sharpening my programming skills is a habit that I have been trying to keep up with for the last three years. This habit is important for my career and it's also an activity that I find to be quite fulfilling. So Beeminding my programming goals was a natural next step.  

Unfortunately, I was left slightly disappointed with [the official `gitminder` integration](https://www.beeminder.com/gitminder){target="_blank"}. The integration only supports data tracking in the following scenarios:

- commits in a single repository
- issues closed in a single repository
- commits across your entire account
- issues closed across your entire account

Having only these scenarios to choose from, Beeminder users are prevented from defining complex programming goals. For example, the configurations above are not flexible enough for a 'learn python' or 'contribute to open source' goal. These goals could span multiple repositories, but would likely not include every repository in my account. Conversely, what if I was learning python AND contributing to open source in a single repository? That scenario would require a single repository connected to multiple goals, which is not possible through `gitminder`. Additionally, programming activity is not just restricted to commits and closed issues. There are many other events on GitHub (e.g. pull requests, opened issues, publishing releases, deployment), that could be used to contribute towards Beeminder goals.

So instead of giving in and manually tracking my programming goals, I built a tool that addresses all of the above concerns.  

# multigitminder

[`multigitminder`](https://github.com/HaydenMacDonald/multigitminder){target="_blank"} is a [GitHub Action](https://github.com/features/actions){target="_blank"} that helps users capture their programming activity as data for their Beeminder goals. This tool allows users to connect any number of GitHub repositories to any number of Beeminder goals based on [any combination of events supported by GitHub Actions](https://docs.github.com/en/actions/reference/events-that-trigger-workflows){target="_blank"}.

## How it works

If you are not familiar with GitHub Actions, it as an automation framework built directly into GitHub. It allows you to automate software development tasks that you would otherwise do manually on GitHub. It is particularly useful for helping software developers maintain and organize their projects throughout all stages of a development cycle. GitHub Actions has a generous free plan available to all users on public repositories, making it especially useful for the open source community.  

So without getting into anymore detail on GitHub Actions, the important thing to know is that `multigitminder` is a tool that automatically captures and sends data to Beeminder based on your specifications.  

After installation, GitHub Actions will run `multigitminder` every time your chosen event type occurs (e.g. commit, closed issue, pull request) in your repository. The action uses a simple python script (via [`pyminder`](https://github.com/narthur/pyminder){target="_blank"}) to push data points to Beeminder's API.  

You can install `multigitminder` on any repository you own by:

- Creating a workflow file in a `.github/workflows/` directory
- Specifying your goal parameters in the workflow file
- Storing your Beeminder username and authorization token as secrets in your repo

A basic workflow file using `multigitminder` would look like this: 

```yaml
name: multigitminder
on:
  push:
    branches: [ main ]

jobs:
  multigitminder:
    runs-on: ubuntu-latest
    name: multigitminder
    steps:
      - name: multigitminder
        uses: HaydenMacDonald/multigitminder@main
        with:
          USERNAME: ${{ secrets.BEEMINDER_USERNAME }}
          AUTH_TOKEN: ${{ secrets.BEEMINDER_AUTH_TOKEN }}
          GOAL: YOUR_GOAL_NAME_HERE
```
&nbsp;  
After adding that workflow file, you can add your secrets to GitHub by going to their repository Settings > Secrets > New Repository Secret. You can retrieve your Beeminder Auth Token from the Apps & API tab in the Account Settings page.  

After this is done, you will have a basic implementation of `multigitminder` that triggers on pushes to the main branch of your repository. From here, you can change your workflow file to suit your programming goal(s).

## Basic Workflows

Perhaps you want data points to be submitted with every push and closed issue:

```yaml
name: multigitminder-issue-closed
on:
  push:
    branches: [ main ]
  issues:
    types: [ closed ]

jobs:
  multigitminder:
    runs-on: ubuntu-latest
    name: multigitminder
    steps:
      - name: multigitminder
        uses: HaydenMacDonald/multigitminder@main
        with:
          USERNAME: ${{ secrets.BEEMINDER_USERNAME }}
          AUTH_TOKEN: ${{ secrets.BEEMINDER_AUTH_TOKEN }}
          GOAL: YOUR_GOAL_NAME_HERE
```
&nbsp;  
Or when pull requests are opened or closed:

```yaml
name: multigitminder-pull-request
on:
  pull_request:
    types: [ opened, closed ]

jobs:
  multigitminder:
    runs-on: ubuntu-latest
    name: multigitminder
    steps:
      - name: multigitminder
        uses: HaydenMacDonald/multigitminder@main
        id: multigitminder
        with:
          USERNAME: ${{ secrets.BEEMINDER_USERNAME }}
          AUTH_TOKEN: ${{ secrets.BEEMINDER_AUTH_TOKEN }}
          GOAL: YOUR_GOAL_NAME_HERE
```
&nbsp;  
Again, `multigitminder` can be configured to trigger on [any combination of events supported by GitHub Actions](https://docs.github.com/en/actions/reference/events-that-trigger-workflows){target="_blank"}. So feel free to experiment with what works best for your Beeminder goals.  

## Additional parameterization

### Specific Commits

`multigitminder` can also be configured so that only specific commits trigger the workflow.

```yaml
name: multigitminder-specific-commits
on:
  push:
    branches: [ main ]

jobs:
  multigitminder:
    if: "contains(github.event.head_commit.message, '[multigitminder]')" ## THIS LINE HERE
    runs-on: ubuntu-latest
    name: multigitminder
    steps:
      - name: multigitminder
        uses: HaydenMacDonald/multigitminder@main
        with:
          USERNAME: ${{ secrets.BEEMINDER_USERNAME }}
          AUTH_TOKEN: ${{ secrets.BEEMINDER_AUTH_TOKEN }}
          GOAL: YOUR_GOAL_NAME_HERE
```
&nbsp;  
In this example, only commits with '[multigitminder]' in the commit message will trigger the workflow.

### Commit Messages as Comments

Additionally, you can use the commit message as the comment for each data point so that you can cross-reference your commits across GitHub and Beeminder.

```yaml
name: multigitminder-commit-message-comment
on:
  push:
    branches: [ main ]

jobs:
  multigitminder:
    runs-on: ubuntu-latest
    name: multigitminder
    steps:
      - name: multigitminder
        uses: HaydenMacDonald/multigitminder@main
        with:
          USERNAME: ${{ secrets.BEEMINDER_USERNAME }}
          AUTH_TOKEN: ${{ secrets.BEEMINDER_AUTH_TOKEN }}
          GOAL: YOUR_GOAL_NAME_HERE
          COMMENT: ${{ github.event.head_commit.message }} ## THIS LINE HERE
```
&nbsp;  

### Language-based Goals

You can configure `multigitminder` to trigger based on the languages in your repository, with the help of [fabasoad/linguist-action](https://github.com/marketplace/actions/linguist-action){target="_blank"}. This configuration ensures that `multigitminder` only triggers if at least one of your target languages are found in the repository code.

```yaml
name: multigitminder-linguist
on:
  push:
    branches: [ main ]

jobs:
  multigitminder:
    runs-on: ubuntu-latest
    name: multigitminder
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      # linguist
      - name: Linguist Action
        uses: fabasoad/linguist-action@v1.0.2
        id: linguist
        with:
          path: './'
          percentage: true
      # multigitminder
      - name: multigitminder
        uses: HaydenMacDonald/multigitminder@main
        id: multigitminder
        with:
          USERNAME: ${{ secrets.BEEMINDER_USERNAME }}
          AUTH_TOKEN: ${{ secrets.BEEMINDER_AUTH_TOKEN }}
          GOAL: YOUR_GOAL_NAME_HERE
          TARGET_LANGS: YOUR_TARGET_LANGUAGES_HERE ## e.g. "['python', 'javascript']"
          REPO_LANGS: ${{ steps.linguist.outputs.data }}
```
&nbsp;  

### One repository to multiple goals

Lastly, what if you want activity in a repository to contribute to multiple Beeminder goals? You can achieve this by creating a workflow file for each goal, changing the input parameters accordingly. For example, I want closed issues in my repository to contribute towards a 'maintenance' Beeminder goal...

```yaml
name: multigitminder-issue-closed
on:
  push:
    branches: [ main ]
  issues:
    types: [ closed ]

jobs:
  multigitminder:
    runs-on: ubuntu-latest
    name: multigitminder
    steps:
      - name: multigitminder
        uses: HaydenMacDonald/multigitminder@main
        with:
          USERNAME: ${{ secrets.BEEMINDER_USERNAME }}
          AUTH_TOKEN: ${{ secrets.BEEMINDER_AUTH_TOKEN }}
          GOAL: YOUR_GOAL_NAME_HERE
```
&nbsp;  
and pushes to the main and development branches to contribute towards a 'write-python' goal (provided python is found in the repo)...

```yaml
name: multigitminder-linguist
on:
  push:
    branches: [ main, dev ]

jobs:
  multigitminder:
    runs-on: ubuntu-latest
    name: multigitminder
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      # linguist
      - name: Linguist Action
        uses: fabasoad/linguist-action@v1.0.2
        id: linguist
        with:
          path: './'
          percentage: true
      # multigitminder
      - name: multigitminder
        uses: HaydenMacDonald/multigitminder@main
        id: multigitminder
        with:
          USERNAME: ${{ secrets.BEEMINDER_USERNAME }}
          AUTH_TOKEN: ${{ secrets.BEEMINDER_AUTH_TOKEN }}
          GOAL: write-python
          TARGET_LANGS: python
          REPO_LANGS: ${{ steps.linguist.outputs.data }}
```
&nbsp;  
With both of these workflow files in my `./github/workflows` directory, they will trigger independently of one another, according to their specifications.  

## Conclusion

If this project interests you, please experiment with `multigitminder`! I hope this tools opens the doors for modular programming goals in Beeminder. At least until the official GitHub integration becomes more flexible `r emo::ji("smile")`  


## Help

If you find a bug or have an idea on how to improve `multigitminder`, please submit an issue on [GitHub](https://github.com/HaydenMacDonald/multigitminder/issues){target="_blank"} or send me an email at hmd[at]needleinthehay.ca. 



