theme: hugo-PaperMod
baseURL: 'https://needleinthehay.ca/'
languageCode: en-us
title: Needle in the Hay
googleAnalytics: UA-125960941-1
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
menu:
  main:
    - identifier: archives
      name: Blog
      url: /archives/
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 20
    - identifier: resume
      name: Resume
      url: /cv.pdf
      weight: 30
    - identifier: data-gallery
      name: Data Gallery
      url: /data-gallery/
      weight: 40
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 50
params:
  env: production
  title: NeedleInTheHay
  description: A Data Blog
  author: Hayden MacDonald
  images:
    - /hay.jpg
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  disableSpecial1stPost: false
  comments: false
  hidemeta: false
  showtoc: false
  tocopen: false
  math: true
  homeInfoParams:
    Title: Hi I'm Hayden
    Content: This is my data analytics blog!
  profileMode:
    enabled: true
    title: Hayden MacDonald
    imageUrl: /headshotbw.jpg
    imageTitle: That's me!
    imageWidth: 120
    imageHeight: 120
  socialIcons:
    - name: email
      url: 'mailto:hmd@needleinthehay.ca'
    - name: linkedin
      url: 'https://www.linkedin.com/in/hayden-macdonald/'
    - name: github
      url: 'https://github.com/HaydenMacDonald'
    - name: twitter
      url: 'https://twitter.com/HYDNMCDNLD'
  assets:
    favicon: /favicon.ico
    favicon16x16: /favicon-16x16.png
    favicon32x32: /favicon-32x32.png
    apple_touch_icon: /apple-touch-icon.png
    disableHLJS: false
  label:
    text: Needle in the Hay
    icon: /apple-touch-icon-2.png
    iconDark: /apple-touch-icon-dark.png
    iconHeight: 35
    iconWidth: 40
  analytics:
    google:
      SiteVerificationTag: "UA-125960941-1"
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content
outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  goldmark:
    renderer:
      unsafe: true
