theme: "hugo-PaperMod"
baseURL: http://needleinthehay.ca/
languageCode: en-us
title: Needle in the Hay

menu:
    main:
        - identifier: archives
          name: Blog
          url: /archives/
          weight: 10
        - identifier: about
          name: About
          url: /about/
          weight: 20
        - identifier: resume
          name: Resume
          url: /cv/
          weight: 30
        - identifier: data-gallery
          name: Data Gallery
          url: /data-gallery/
          weight: 40
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 50

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: NeedleInTheHay
    description: "ExampleSite description"
    author: Hayden MacDonald
    images: ["<link or path of image for opengraph, twitter-cards>"]

    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    disableSpecial1stPost: false
    comments: false
    hidemeta: false
    showtoc: false
    tocopen: false

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

pygmentsUseClasses: true
markup:
     highlight:
         # anchorLineNos: true
         codeFences: true
         guessSyntax: true
         lineNos: false
         style: monokai

