---
title: About Me
subtitle:
comments: false
hidemeta: true
---

My name is Hayden MacDonald and I am a Canadian-British data analyst.  

This is my data blog. To read through previous posts, see the <a href="/archives">Blog section</a>. 

I hold a Master of Science in Management &#8211; Business Analytics from Ivey Business School, Western University. For a full list of my credentials, see <a href="/cv.pdf" target="_blank">my resume</a>.  

My professional interests include technology, research, statistics, A/B testing, data visualization, and product analytics. In my spare time, I enjoy contributing to open source, cooking, SCUBA diving, and hiking. I also love watching movies, football, squash, and eSports.  
&nbsp;  

### Why is your blog called "Needle in the Hay"?
  
I chose <a href="https://dictionary.cambridge.org/dictionary/english/a-needle-in-a-haystack" target="_blank">"Needle in the Hay"</a> because it is an analogy for the diligent search for the right questions, among all *possible* questions.  

My career mission is to use data analytics to sift through the "hay" in search of the "needle" when addressing new world business problems.  
&nbsp;  
 
### What should I expect to see on this blog?  
  
My goal for this blog is to create quality content that documents my professional growth in programming and analytics. My posts will contain educational content, but may also contain personal reflections or opinions. Most of my posts will use the `R` programming language but, as I continue learning, I plan to include `Python` and `SQL` as well.  
&nbsp;  

----

### Open Source

#### Author

- <a href="https://github.com/HaydenMacDonald/squashinformr" target="_blank">`squashinformr`</a>
- <a href="https://github.com/marketplace/actions/multigitminder" target="_blank">`multigitminder`</a>

#### Contributor

- <a href="https://github.com/davidsjoberg/ggbump" target="_blank">`ggbump`</a>
- <a href="https://github.com/amosbastian/fpl" target="_blank">`fpl`</a>
- <a href="https://github.com/johncassil/stringr.plus" target="_blank">`stringr.plus`</a>
- <a href="https://github.com/HaydenMacDonald/lubridateExtras" target="_blank">`lubridateExtras`</a>
- <a href="https://github.com/philip-khor/bnmr" target="_blank">`bnmr`</a>

----

### Publications
**MacDonald, Hayden**, Lo, G. K. H., Macpherson, K., & Roberts, W.A. (2020). An isolation effect in rat spatial memory. *JEP: Anim Learn and Cogn*. doi: <a href="https://psycnet.apa.org/record/2019-72853-001" target="_blank">10.1037/xan0000231</a>.

**MacDonald, Hayden**. (2018). Spatial memory for isolated arm locations on the radial maze. *Electronic Thesis and Dissertation Repository*. <a href="https://ir.lib.uwo.ca/etd/5511" target="_blank">5511</a>.  

Roberts, W. A., **MacDonald, H.** & Lo, K. H. (2018). Pigeons play the percentages: Computation of probability in a bird. *Anim Cogn*, *21*(4), 575-581. doi: <a href="https://link.springer.com/article/10.1007%2Fs10071-018-1192-0" target="_blank">10.1007/s10071-018-1192-0</a>

**MacDonald, H.**, & Roberts, W.A. (2018). Cognitive flexibility and dual processing in pigeons: Temporal and contextual control of midsession reversal. *J Exp Psychol Anim Learn Cogn*, *44*(2), 149-161. doi: <a href="http://psycnet.apa.org/record/2018-07553-001" target="_blank">10.1037/xan0000161</a>

Roberts, W.A., **MacDonald, H.**, Brown, L., & Macpherson, K. (2017). Release from proactive interference in rat spatial working memory. *Learn Behav*, *45*(3), 263-275. doi: <a href="https://link.springer.com/article/10.3758%2Fs13420-017-0263-4" target="_blank">10.3758/s13420-017-0263-4</a>

Roberts, W.A., Guitar, N.A., Marsh, H.L., & **MacDonald, H.** (2016). Memory systems in the rat: effects of reward probability, context, and congruency between working and reference memory. *Anim Cogn*, *19*(3), 593-604. doi: <a href="https://link.springer.com/article/10.1007%2Fs10071-016-0964-7" target="_blank">10.1007/s10071-016-0964-7</a>  

-------

### Conferences & Workshops
**MacDonald, H.** (2019, February) Ivey BA R Workshop - Intro to the Tidyverse. 2 hour workshop presented at Ivey Business School. <a href="https://drive.google.com/file/d/1lW2JloOUYSpNkdT8xwR84ZDXGClAJrf5/view?usp=sharing" target="_blank">PDF slides</a>.

**MacDonald, H.**, & Roberts, W. A. (2018, April). Spatial memory for isolated arm locations on the radial maze. Five minute talk presented at the International Conference On Comparative Cognition, Melbourne, Florida.

**MacDonald, H.**, & Roberts, W. A. (2017, April). Time versus context in a visual mid-session reversal task. Poster presented at the International Conference On Comparative Cognition, Melbourne, Florida.  

----
&nbsp;  
This blog is built with R, the <a href="https://github.com/rstudio/blogdown" target="_blank">blogdown package</a>, <a href="https://gohugo.io/" target="_blank">Hugo</a>, the <a href="https://github.com/adityatelange/hugo-PaperMod" target="_blank">hugo-PaperMod theme</a> and deployed using <a href="https://www.netlify.com/" target="_blank">Netlify</a>. Content published on my blog is released under a <a href="https://github.com/HaydenMacDonald/needle-in-the-hay/blob/master/LICENSE" target="_blank">MIT License</a>.  
&nbsp;  
  
